apiVersion: v1
kind: Service
metadata:
  name: faktura-app
  namespace: faktura
spec:
  selector:
    app: faktura-app

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: ClusterIP